#!/usr/bin/bash

segment="
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBZZZZZZZZZZZZZZCCCCCCCCCCCCCCCCCCCCC 
AaaaaaAAaAAAaAAAaaaAAAaAAAaABBbbbbBBbbbbbBBbBBBbBBbbbbBBBbbbbbBBbBBBBBBBbbbBBBbBBBbBZzzzzZZZzzzzZZCccccCCCcCCCcCCCcccCC 
AaAAAAAAaaAAaAAaAAAaAAaaAaaABbBBBBBBbBBBBBBbbBbbBBbBBBbBBBBbBBBBbBBBBBBbBBBbBBbbBBbBZzZZZzZZzZZZzZCcCCCcCCcCCCcCCcCCCcC 
AaaaaAAAaAaAaAAaAAAaAAaAaAaABBbbbBBBbbbbBBBbBbBbBBbbbbBBBBBbBBBBbBBBBBBbBBBbBBbBbBbBZzzzzZZZzzzzZZCcCCCcCCcCCCcCCcCCCcC 
AaAAAAAAaAAaaAAaaaaaAAaAAAaABBBBBbBBbBBBBBBbBBBbBBbBBBbBBBBbBBBBbBBBBBBbbbbbBBbBBbbBZzZZZzZZzZzZZZCcCCCcCCcCCCcCCcccccC 
AaaaaaAAaAAAaAAaAAAaAAaAAAaABbbbbBBBbbbbbBBbBBBbBBbbbbBBBbbbbbBBbbbbbBBbBBBbBBbBBBbBZzzzzZZZzZZzZZCccccCCCCcccCCCcCCCcC 
AAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBZZZZZZZZZZZZZZCCCCCCCCCCCCCCCCCCCCC 
DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
DdddddDDdddddDDDddddDDDdddDDEEeeeeEEeeeeeEFffffFFFfffffFFfFFFFFFFfffFFGGggggGHhhhhhHHhhhhHHHhHHHhHHhHHHHHHhHHHhHHhHHHhH
DDDdDDDDDDdDDDDdDDDDDDdDDDdDEeEEEEEEeEEEEEFfFFFfFFfFFFFFFfFFFFFFfFFFfFGgGGGGGHhHHHHHHhHHHhHHhHHHhHHhHHHHHHhHHHhHHhHHHhH
DDDdDDDDDDdDDDDdDdddDDdDDDdDEEeeeEEEeeeeEEFffffFFFffffFFFfFFFFFFfFFFfFGGgggGGHhhhhHHHhhhhHHHhHHHhHHhHHHHHHhHHHhHHhhhhhH
DDDdDDDDDDdDDDDdDDDdDDdddddDEEEEEeEEeEEEEEFfFFFfFFfFFFFFFfFFFFFFfffffFGGGGGgGHhHHHHHHhHHHHHHhHHHhHHhHHHHHHhHHHhHHhHHHhH
DDDdDDDDdddddDDDddddDDdDDDdDEeeeeEEEeeeeeEFffffFFFfffffFFfffffFFfFFFfFGggggGGHhhhhhHHhHHHHHHHhhhHHHhhhhhHHHhhhHHHhHHHhH
DDDDDDDDDDDDDDDDDDDDDDDDDDDDEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
IIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMM
IIiiiiIIIiiiIIIiiiiiIIiIIIiIJjJJJJJJjjjjjJJjJJJjJJJjjjJJKkkkkkKKkKKKkKKkkkkKKKKkkkKKLlllllLMmMMMmMMMMMMmMMmMMMmMMmMMMmM
IiIIIIIIiIIIiIIIIiIIIIiIIIiIJjJJJJJJJJjJJJJjjJjjJJjJJJjJKkKKKKKKkkKkkKKkKKKkKKkKKKkKLLLlLLLMmMMMmMMMMMMmMMmMMMmMMmMMMmM
IIiiiIIIiIIIiIIIIiIIIIiIIIiIJjJJJJJJJJjJJJJjJjJjJJjJJJjJKkkkkKKKkKkKkKKkkkkKKKkKKKkKLLLlLLLMmMMMmMMMMMMmMMmMMMmMMmmmmmM
IIIIIiIIiiiiiIIIIiIIIIiIIIiIJjJJJJJJJJjJJJJjJJJjJJjjjjjJKkKKKKKKkKKKkKKkKKKKKKkkkkkKLLLlLLLMmMMMmMMmMMMmMMmMMMmMMmMMMmM
IiiiiIIIiIIIiIIIIiIIIIIiiiIIJjjjjjJJjjjjjJJjJJJjJJjJJJjJKkkkkkKKkKKKkKKkKKKKKKkKKKkKLLLlLLLMMmmmMMMMmmmMMMMmmmMMMmMMMmM
IIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLMMMMMMMMMMMMMMMMMMMMMMMMMMMM
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZZZZZZZOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPP
NnnnnNNNnnnnnNNnNNNNNNNnnnNNNnnnnNNNNnnnNNNnNNNnNZZzzzZZOoOOOoOOoOOOoOOooooOOOOoooOOOoOOOoOOOooooOPppppPPPPpppPPPPppppP
NnNNNnNNnNNNNNNnNNNNNNnNNNnNNnNNNnNNnNNNnNNnnNNnNZzZZZzZOoOOoOOOoOOOoOOoOOOoOOoOOOoOOooOOoOOoOOOOOPpPPPpPPpPPPpPPpPPPPP
NnNNNnNNnnnnNNNnNNNNNNnNNNnNNnnnnNNNnNNNnNNnNnNnNZzZZZzZOoooOOOOoOOOoOOooooOOOoOOOoOOoOoOoOOoOoooOPppppPPPpPPPpPPPpppPP
NnNNNnNNnNNNNNNnNNNNNNnnnnnNNnNNNNNNnnnnnNNnNNnnNZzZZZzZOoOOoOOOoOOOoOOoOoOOOOoooooOOoOOooOOoOOOoOPpPPPPPPpppppPPPPPPpP
NnnnnNNNnnnnnNNnnnnnNNnNNNnNNnNNNNNNnNNNnNNnNNNnNZZzzzZZOoOOOoOOOoooOOOoOOoOOOoOOOoOOoOOOoOOOooooOPpPPPPPPpPPPpPPppppPP
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZZZZZZZOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPP
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQZZZZZZZRRRRRRRRRRRRRRRRRRRRRSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTT
QqQQQQQQqqqqqQQqqqqQQQqqqqqQQqQQQqQZZzzzZZRrrrrRRRrRRRrRRRrrrRRSsssssSSsssssSSSssssSSSsssSSTtTTTTTTtttttTTtTTTtTTTtttTT
QqQQQQQQqQQQQQQqQQQqQQQQqQQQQqQQQqQZzZZZzZRrRRRrRRrRRRrRRrRRRrRSSSsSSSSSSsSSSSsSSSSSSsSSSsSTtTTTTTTTTtTTTTttTttTTtTTTtT
QqQQQQQQqqqqQQQqqqqQQQQQqQQQQqqqqqQZzZzZzZRrRRRrRRrRRRrRRrRRRrRSSSsSSSSSSsSSSSsSsssSSsSSSsSTtTTTTTTTTtTTTTtTtTtTTtTTTtT
QqQQQQQQqQQQQQQqQQQqQQQQqQQQQqQQQqQZzZZzZZRrRRRrRRrRRRrRRrrrrrRSSSsSSSSSSsSSSSsSSSsSSsssssSTtTTTTTTTTtTTTTtTTTtTTtttttT
QqqqqqQQqqqqqQQqqqqQQQqqqqqQQqQQQqQZZzzZzZRrrrrRRRRrrrRRRrRRRrRSSSsSSSSsssssSSSssssSSsSSSsSTtttttTTtttttTTtTTTtTTtTTTtT
QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQZZZZZZZRRRRRRRRRRRRRRRRRRRRRSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTT
UUUUUUUUUUUUUUUUUUUUUUUUUUUUVVVVVVVWWWWWWWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZZZZZYYYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZ
UuuuuUUUuuuuuUUuUUUUUUUuuuUUVVvvvvVWwwwwwWXxxxxXXXxXXXxXXxXXXXXXxXXXxXXxXXXxXZzZZZzZYyYYYYYYyyyyyYYyYYYyYYYyyyYYZzZZZzZ
UuUUUuUUuUUUUUUuUUUUUUuUUUuUVvVVVVVWwWWWWWXxXXXxXXxXXXxXXxXXXXXXxXXXxXXxXXXxXZzZZzZZYyYYYYYYYYyYYYYyyYyyYYyYYYyYZZzZzZZ
UuuuuUUUuuuuUUUuUUUUUUuUUUuUVVvvvVVWwwwwWWXxxxxXXXxXXXxXXxXXXXXXxXXXxXXxxxxxXZzzzZZZYyYYYYYYYYyYYYYyYyYyYYyYYYyYZZZzZZZ
UuUUUuUUuUUUUUUuUUUUUUuuuuuUVVVVVvVWwWWWWWXxXXXXXXxXXXxXXxXXXXXXxXXXxXXxXXXxXZzZZzZZYyYYYYYYYYyYYYYyYYYyYYyyyyyYZZzZzZZ
UuuuuUUUuuuuuUUuuuuuUUuUUUuUVvvvvVVWwwwwwWXxXXXXXXXxxxXXXxxxxxXXXxxxXXXxXXXxXZzZZZzZYyyyyyYYyyyyyYYyYYYyYYyYYYyYZzZZZzZ
UUUUUUUUUUUUUUUUUUUUUUUUUUUUVVVVVVVWWWWWWWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXZZZZZZZYYYYYYYYYYYYYYYYYYYYYYYYYYYYZZZZZZZ"
segment=${segment:1:10000}

while true; do
	clear
	hms=$( date +"%I%M%S" | sed s/^12/00/ )
	ms=${hms:2:4}
    h=cfg
	cps=( 113000 103000 093000 083000 073000 063000 053000 043000 033000 023000 013000 003000 )
    seg=( cfg    efg    gh     b      n      lm     a      j      kl     d      c      i      )
#a   b         c
#ENAMSEMBILAN--DUA
#d   e f   gh
#TIGASEBELASEPULUH
#i   j   k   lm
#SATULIMAEMPATUJUH
#n       o     p
#DELAPAN-KURANGPAS
#q     r  s   t
#LEBIH-DUATIGALIMA
#u   vwx     y
#BELASEPULUH-LIMA-
	for i in "${!cps[@]}"; do
		if [[ "${cps[$i]}" < "$hms" ]]; then
			h=${seg[$i]}
			break
		fi
	done
	m=p
    next=0130
	cps=( 6000 5900 5730 5600 5230 4900 4730 4600 4230 3730 3230 3000 2730 2230 1730 1400 1230 1100 0730 0400 0230 0130 )
	seg=( p    p    or   os   ot   ovwx oruv osuv otuv orx  orxy osx  qsx  qrxy qrx  qtuv qsuv qruv qvwx qt   qs   qr   )
	for i in "${!cps[@]}"; do
		if [[ "${cps[$i]}" < "$ms" ]]; then
			m=${seg[$i]}
			next=${cps[$i-1]}
			break
		fi
	done
	on=$( echo 'abcdefghijklmnopqrstuvwxyz' | tr "$h$m" "${h^^}${m^^}" )
	clock=$( printf "$( echo "$segment" | tr "$on" '#' | tr "${on~~}" "." | sed -E 's/(^|\.)#/\1\\e[47m#/g; s/(^|#)\./\1\\e[0m./g; s/$/\\e[0m/g; s/(#|\.)/ /g' )" )
	tw=$(tput cols)
	th=$(tput lines)
	py=$(( (th / 2) - (42 / 2) ))
	px=$(( (tw / 2) - (119 / 2) ))
	current_y=$py
	while IFS= read -r line; do
		tput cup $current_y $px
		echo "$line"
		((current_y++))
	done <<< "$clock"
	tput cup $th 0
	sleep=$(( 60 * ( 1${next:0:2} - 1${ms:0:2} ) + 1${next:2:2} - 1${ms:2:2} + 1 ))
	#echo "Updated on" $( date +"%Y-%m-%d %a %H:%M:%S" ) "sleep" $sleep "s"
	sleep $sleep
done
